name: 'Email Notification'
description: 'Send email notification on workflow failure'

inputs:
  email:
    description: 'Email address to send notification to'
    required: true
  subject:
    description: 'Email subject'
    required: true
  html_content:
    description: 'HTML content for the email body'
    required: true
  gmail_user:
    description: 'Gmail address to send from'
    required: true
  gmail_app_password:
    description: 'Gmail app password'
    required: true

runs:
  using: "composite"
  steps:
    - name: Send Email Notification
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        secure: true
        ignore_cert: true
        username: ${{ inputs.gmail_user }}
        password: ${{ inputs.gmail_app_password }}
        subject: ${{ inputs.subject }}
        to: ${{ inputs.email }}
        from: ${{ inputs.gmail_user }}
        html_body: ${{ inputs.html_content }} 