# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deployment

on:
  release:
    types: [published]
    branches: [master]
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  deploy-website:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Packaging
      run: |
        npm ci
        npm run build --if-present
    - name: Firebase deployment
      env: 
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: |
        npm run notify-deployment
        npm run deploy
  upload-resume:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Firebase deployment
      env: 
        DROPBOX_ACCESS_TOKEN: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
      run: |
        echo Testing `date` >> resume.docx
        curl -X POST https://content.dropboxapi.com/2/files/upload \
          --header "Authorization: Bearer ${DROPBOX_ACCESS_TOKEN}" \
          --header "Dropbox-API-Arg: {\"path\": \"/alpha/resume.docx\",\"mode\": \"overwrite\",\"autorename\": false,\"mute\": false,\"strict_conflict\": false}" \
          --header "Content-Type: application/octet-stream" \
          --data-binary @resume.docx

