name: Process Resume

on:
  push:
    branches:
      - master
    paths:
      - data/resume/docs/resume*.docx

jobs:
  create-resumes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up permissions
        run: chmod +x data/resume/bin/create-resumes.sh

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build JAR
        working-directory: data/resume
        run: |
          ./gradlew build

      - name: Run resume creation script
        working-directory: data/resume
        run: ./bin/create-resumes.sh

      - name: Upload DOCX to Dropbox
        uses: ./.github/actions/dropbox-upload
        with:
          file_pattern: 'docs/resume*.docx'
          dropbox_path: '/about/resume'
          working_directory: 'data/resume'
          token: ${{ secrets.DROPBOX_ACCESS_TOKEN }}

      - name: Upload DOCX as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: resume-docx
          path: data/resume/docs/resume*.docx
          if-no-files-found: error

  convert-to-pdf:
    needs: create-resumes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download DOCX artifacts
        uses: actions/download-artifact@v4
        with:
          name: resume-docx
          path: data/resume/docs

      - name: Convert DOCX to PDF
        if: false
        uses: ./.github/actions/docx-to-pdf
        with:
          file_pattern: 'docs/resume*.docx'
          working_directory: 'data/resume'

      - name: Temporary PDF Creation
        run: |
          touch data/resume/docs/resume-sde.pdf
          touch data/resume/docs/resume-ml.pdf


      - name: Upload PDF to Dropbox
        if: false
        uses: ./.github/actions/dropbox-upload
        with:
          file_pattern: 'docs/resume*.pdf'
          dropbox_path: '/about/resume'
          working_directory: 'data/resume'
          token: ${{ secrets.DROPBOX_ACCESS_TOKEN }}

      - name: Upload PDF as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: resume-pdf
          path: data/resume/docs/resume*.pdf
          if-no-files-found: error

  update-git:
    needs: [create-resumes, convert-to-pdf]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: data/resume/docs

      - name: Create and push to git branch
        run: |
          git config user.email "afzalex.store@gmail.com"
          git config user.name "afzalex bot"
          git checkout -b fzbot
          git reset --hard master
          
          ls -la data/resume/docs

          # Copy all generated files to docs/assets
          mkdir -p docs/assets
          cp data/resume/docs/resume-docx/*.docx docs/assets/ 2>/dev/null || true
          cp data/resume/docs/resume-pdf/*.pdf docs/assets/ 2>/dev/null || true
          
          git add docs/assets/*
          git commit -m "Added generated resume files"
          git fetch
          git branch --set-upstream-to=origin/fzbot fzbot
          git push -f

  notify-failure:
    needs: [create-resumes, convert-to-pdf, update-git]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Send Email Notification
        uses: ./.github/actions/notify-email
        with:
          email: 'mohammadafzal.tech@gmail.com'
          subject: 'Workflow Failure ❌'
          html_content: |
            <h3>Workflow Failure ❌</h3>
            <p>The workflow "Process Resume" has failed.</p>
            <p><strong>Repository:</strong> ${{ github.repository }}</p>
            <p><strong>Run ID:</strong> ${{ github.run_id }}</p>
            <p>View the workflow run: <a href="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}">Click here</a></p>
          gmail_user: ${{ secrets.GMAIL_USER }}
          gmail_app_password: ${{ secrets.GMAIL_APP_PASSWORD }}

  notify-success:
    needs: [create-resumes, convert-to-pdf, update-git]
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List generated files
        id: list-files
        run: |
          echo "files<<EOF" >> $GITHUB_OUTPUT
          for file in data/resume/docs/resume*.{docx,pdf}; do
            if [ -f "$file" ]; then
              filename=$(basename "$file")
              echo "- [$filename](https://raw.githubusercontent.com/${{ github.repository }}/fzbot/docs/assets/$filename)" >> $GITHUB_OUTPUT
            fi
          done
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Process HTML template
        id: process-template
        run: |
          export REPOSITORY="${{ github.repository }}"
          export RUN_ID="${{ github.run_id }}"
          export FILES_LIST="${{ steps.list-files.outputs.files }}"
          envsubst < .github/templates/success.html > processed_template.html
          cat processed_template.html
          echo "html=$(base64 -w 0 processed_template.html)" >> $GITHUB_OUTPUT

      - name: Send Email Notification
        uses: ./.github/actions/notify-email
        with:
          email: 'mohammadafzal.tech@gmail.com'
          subject: '✨ Resume Generation Complete'
          html_content: ${{ base64 -d <<< steps.process-template.outputs.html }}
          gmail_user: ${{ secrets.GMAIL_USER }}
          gmail_app_password: ${{ secrets.GMAIL_APP_PASSWORD }}
